import type { NodeCategory, NodeCategoryGroup, NodeTypeConfig } from '@/types/funnel'

export const ALL_NODE_CONFIGS: NodeTypeConfig[] = [
  // Traffic Sources (16 types)
  {
    category: 'google_ads',
    group: 'traffic',
    label: 'Google Ads',
    iconName: 'Search',
    primaryColor: '#4285F4',
    secondaryColor: '#34A853',
    backgroundColor: '#E8F0FE',
    borderColor: '#4285F4',
    textColor: '#1a1a1a',
  },
  {
    category: 'facebook_ads',
    group: 'traffic',
    label: 'Facebook Ads',
    iconName: 'Facebook',
    primaryColor: '#1877F2',
    secondaryColor: '#42B72A',
    backgroundColor: '#E7F3FF',
    borderColor: '#1877F2',
    textColor: '#1a1a1a',
  },
  {
    category: 'instagram_ads',
    group: 'traffic',
    label: 'Instagram Ads',
    iconName: 'Instagram',
    primaryColor: '#E4405F',
    secondaryColor: '#F77737',
    backgroundColor: '#FFF0F3',
    borderColor: '#E4405F',
    textColor: '#1a1a1a',
  },
  {
    category: 'tiktok_ads',
    group: 'traffic',
    label: 'TikTok Ads',
    iconName: 'Music',
    primaryColor: '#000000',
    secondaryColor: '#FE2C55',
    backgroundColor: '#F0F0F0',
    borderColor: '#000000',
    textColor: '#1a1a1a',
  },
  {
    category: 'linkedin_ads',
    group: 'traffic',
    label: 'LinkedIn Ads',
    iconName: 'Linkedin',
    primaryColor: '#0A66C2',
    secondaryColor: '#05A6F0',
    backgroundColor: '#E3F2FD',
    borderColor: '#0A66C2',
    textColor: '#1a1a1a',
  },
  {
    category: 'youtube_ads',
    group: 'traffic',
    label: 'YouTube Ads',
    iconName: 'Youtube',
    primaryColor: '#FF0000',
    secondaryColor: '#282828',
    backgroundColor: '#FFE5E5',
    borderColor: '#FF0000',
    textColor: '#1a1a1a',
  },
  {
    category: 'twitter_ads',
    group: 'traffic',
    label: 'Twitter Ads',
    iconName: 'Twitter',
    primaryColor: '#1DA1F2',
    secondaryColor: '#14171A',
    backgroundColor: '#E1F5FE',
    borderColor: '#1DA1F2',
    textColor: '#1a1a1a',
  },
  {
    category: 'pinterest_ads',
    group: 'traffic',
    label: 'Pinterest Ads',
    iconName: 'Pinterest',
    primaryColor: '#E60023',
    secondaryColor: '#000000',
    backgroundColor: '#FFEBEE',
    borderColor: '#E60023',
    textColor: '#1a1a1a',
  },
  {
    category: 'snapchat_ads',
    group: 'traffic',
    label: 'Snapchat Ads',
    iconName: 'Camera',
    primaryColor: '#FFFC00',
    secondaryColor: '#000000',
    backgroundColor: '#FFFDE7',
    borderColor: '#FFFC00',
    textColor: '#1a1a1a',
  },
  {
    category: 'reddit_ads',
    group: 'traffic',
    label: 'Reddit Ads',
    iconName: 'MessageCircle',
    primaryColor: '#FF4500',
    secondaryColor: '#0079D3',
    backgroundColor: '#FFF0E6',
    borderColor: '#FF4500',
    textColor: '#1a1a1a',
  },
  {
    category: 'affiliate',
    group: 'traffic',
    label: 'Affiliate',
    iconName: 'Users',
    primaryColor: '#8B5CF6',
    secondaryColor: '#7C3AED',
    backgroundColor: '#F3E8FF',
    borderColor: '#8B5CF6',
    textColor: '#1a1a1a',
  },
  {
    category: 'organic_search',
    group: 'traffic',
    label: 'Organic Search',
    iconName: 'Globe',
    primaryColor: '#10B981',
    secondaryColor: '#059669',
    backgroundColor: '#D1FAE5',
    borderColor: '#10B981',
    textColor: '#1a1a1a',
  },
  {
    category: 'direct',
    group: 'traffic',
    label: 'Direct',
    iconName: 'Zap',
    primaryColor: '#F59E0B',
    secondaryColor: '#D97706',
    backgroundColor: '#FEF3C7',
    borderColor: '#F59E0B',
    textColor: '#1a1a1a',
  },
  {
    category: 'email_marketing',
    group: 'traffic',
    label: 'Email Marketing',
    iconName: 'Mail',
    primaryColor: '#3B82F6',
    secondaryColor: '#2563EB',
    backgroundColor: '#DBEAFE',
    borderColor: '#3B82F6',
    textColor: '#1a1a1a',
  },
  {
    category: 'podcast',
    group: 'traffic',
    label: 'Podcast',
    iconName: 'Mic',
    primaryColor: '#EC4899',
    secondaryColor: '#DB2777',
    backgroundColor: '#FCE7F3',
    borderColor: '#EC4899',
    textColor: '#1a1a1a',
  },
  {
    category: 'webinar',
    group: 'traffic',
    label: 'Webinar',
    iconName: 'Video',
    primaryColor: '#6366F1',
    secondaryColor: '#4F46E5',
    backgroundColor: '#E0E7FF',
    borderColor: '#6366F1',
    textColor: '#1a1a1a',
  },
  // Pages (12 types)
  {
    category: 'landing_page',
    group: 'page',
    label: 'Landing Page',
    iconName: 'LayoutTemplate',
    primaryColor: '#0EA5E9',
    secondaryColor: '#0284C7',
    backgroundColor: '#E0F2FE',
    borderColor: '#0EA5E9',
    textColor: '#1a1a1a',
  },
  {
    category: 'sales_page',
    group: 'page',
    label: 'Sales Page',
    iconName: 'ShoppingCart',
    primaryColor: '#F97316',
    secondaryColor: '#EA580C',
    backgroundColor: '#FFEDD5',
    borderColor: '#F97316',
    textColor: '#1a1a1a',
  },
  {
    category: 'checkout',
    group: 'page',
    label: 'Checkout',
    iconName: 'CreditCard',
    primaryColor: '#22C55E',
    secondaryColor: '#16A34A',
    backgroundColor: '#DCFCE7',
    borderColor: '#22C55E',
    textColor: '#1a1a1a',
  },
  {
    category: 'thank_you',
    group: 'page',
    label: 'Thank You Page',
    iconName: 'CheckCircle',
    primaryColor: '#14B8A6',
    secondaryColor: '#0D9488',
    backgroundColor: '#CCFBF1',
    borderColor: '#14B8A6',
    textColor: '#1a1a1a',
  },
  {
    category: 'blog_post',
    group: 'page',
    label: 'Blog Post',
    iconName: 'FileText',
    primaryColor: '#64748B',
    secondaryColor: '#475569',
    backgroundColor: '#F1F5F9',
    borderColor: '#64748B',
    textColor: '#1a1a1a',
  },
  {
    category: 'webinar_registration',
    group: 'page',
    label: 'Webinar Registration',
    iconName: 'Calendar',
    primaryColor: '#8B5CF6',
    secondaryColor: '#7C3AED',
    backgroundColor: '#F3E8FF',
    borderColor: '#8B5CF6',
    textColor: '#1a1a1a',
  },
  {
    category: 'survey',
    group: 'page',
    label: 'Survey',
    iconName: 'ClipboardList',
    primaryColor: '#A855F7',
    secondaryColor: '#9333EA',
    backgroundColor: '#FAE8FF',
    borderColor: '#A855F7',
    textColor: '#1a1a1a',
  },
  {
    category: 'calendar',
    group: 'page',
    label: 'Calendar Booking',
    iconName: 'CalendarCheck',
    primaryColor: '#06B6D4',
    secondaryColor: '#0891B2',
    backgroundColor: '#CFFAFE',
    borderColor: '#06B6D4',
    textColor: '#1a1a1a',
  },
  {
    category: 'order_page',
    group: 'page',
    label: 'Order Page',
    iconName: 'Package',
    primaryColor: '#F59E0B',
    secondaryColor: '#D97706',
    backgroundColor: '#FEF3C7',
    borderColor: '#F59E0B',
    textColor: '#1a1a1a',
  },
  {
    category: 'upsell',
    group: 'page',
    label: 'Upsell Page',
    iconName: 'TrendingUp',
    primaryColor: '#EF4444',
    secondaryColor: '#DC2626',
    backgroundColor: '#FEE2E2',
    borderColor: '#EF4444',
    textColor: '#1a1a1a',
  },
  {
    category: 'vsl',
    group: 'page',
    label: 'Video Sales Letter',
    iconName: 'PlayCircle',
    primaryColor: '#DC2626',
    secondaryColor: '#B91C1C',
    backgroundColor: '#FEE2E2',
    borderColor: '#DC2626',
    textColor: '#1a1a1a',
  },
  {
    category: 'bridge_page',
    group: 'page',
    label: 'Bridge Page',
    iconName: 'ArrowRightLeft',
    primaryColor: '#7C3AED',
    secondaryColor: '#6D28D9',
    backgroundColor: '#EDE9FE',
    borderColor: '#7C3AED',
    textColor: '#1a1a1a',
  },
  // Events (10 types)
  {
    category: 'email',
    group: 'event',
    label: 'Email Sent',
    iconName: 'Mail',
    primaryColor: '#3B82F6',
    secondaryColor: '#2563EB',
    backgroundColor: '#DBEAFE',
    borderColor: '#3B82F6',
    textColor: '#1a1a1a',
  },
  {
    category: 'sms',
    group: 'event',
    label: 'SMS Sent',
    iconName: 'MessageSquare',
    primaryColor: '#10B981',
    secondaryColor: '#059669',
    backgroundColor: '#D1FAE5',
    borderColor: '#10B981',
    textColor: '#1a1a1a',
  },
  {
    category: 'phone_call',
    group: 'event',
    label: 'Phone Call',
    iconName: 'Phone',
    primaryColor: '#0EA5E9',
    secondaryColor: '#0284C7',
    backgroundColor: '#E0F2FE',
    borderColor: '#0EA5E9',
    textColor: '#1a1a1a',
  },
  {
    category: 'calendar_event',
    group: 'event',
    label: 'Calendar Event',
    iconName: 'Calendar',
    primaryColor: '#8B5CF6',
    secondaryColor: '#7C3AED',
    backgroundColor: '#F3E8FF',
    borderColor: '#8B5CF6',
    textColor: '#1a1a1a',
  },
  {
    category: 'form_submit',
    group: 'event',
    label: 'Form Submit',
    iconName: 'Send',
    primaryColor: '#F59E0B',
    secondaryColor: '#D97706',
    backgroundColor: '#FEF3C7',
    borderColor: '#F59E0B',
    textColor: '#1a1a1a',
  },
  {
    category: 'video_view',
    group: 'event',
    label: 'Video View',
    iconName: 'Eye',
    primaryColor: '#EC4899',
    secondaryColor: '#DB2777',
    backgroundColor: '#FCE7F3',
    borderColor: '#EC4899',
    textColor: '#1a1a1a',
  },
  {
    category: 'link_click',
    group: 'event',
    label: 'Link Click',
    iconName: 'MousePointerClick',
    primaryColor: '#6366F1',
    secondaryColor: '#4F46E5',
    backgroundColor: '#E0E7FF',
    borderColor: '#6366F1',
    textColor: '#1a1a1a',
  },
  {
    category: 'file_download',
    group: 'event',
    label: 'File Download',
    iconName: 'Download',
    primaryColor: '#14B8A6',
    secondaryColor: '#0D9488',
    backgroundColor: '#CCFBF1',
    borderColor: '#14B8A6',
    textColor: '#1a1a1a',
  },
  {
    category: 'add_to_cart',
    group: 'event',
    label: 'Add to Cart',
    iconName: 'ShoppingCart',
    primaryColor: '#F97316',
    secondaryColor: '#EA580C',
    backgroundColor: '#FFEDD5',
    borderColor: '#F97316',
    textColor: '#1a1a1a',
  },
  {
    category: 'initiate_checkout',
    group: 'event',
    label: 'Initiate Checkout',
    iconName: 'CreditCard',
    primaryColor: '#22C55E',
    secondaryColor: '#16A34A',
    backgroundColor: '#DCFCE7',
    borderColor: '#22C55E',
    textColor: '#1a1a1a',
  },
  // Conversions (6 types)
  {
    category: 'purchase',
    group: 'conversion',
    label: 'Purchase',
    iconName: 'DollarSign',
    primaryColor: '#22C55E',
    secondaryColor: '#16A34A',
    backgroundColor: '#DCFCE7',
    borderColor: '#22C55E',
    textColor: '#1a1a1a',
  },
  {
    category: 'lead',
    group: 'conversion',
    label: 'Lead',
    iconName: 'UserPlus',
    primaryColor: '#3B82F6',
    secondaryColor: '#2563EB',
    backgroundColor: '#DBEAFE',
    borderColor: '#3B82F6',
    textColor: '#1a1a1a',
  },
  {
    category: 'signup',
    group: 'conversion',
    label: 'Sign Up',
    iconName: 'UserCheck',
    primaryColor: '#8B5CF6',
    secondaryColor: '#7C3AED',
    backgroundColor: '#F3E8FF',
    borderColor: '#8B5CF6',
    textColor: '#1a1a1a',
  },
  {
    category: 'subscription',
    group: 'conversion',
    label: 'Subscription',
    iconName: 'Repeat',
    primaryColor: '#EC4899',
    secondaryColor: '#DB2777',
    backgroundColor: '#FCE7F3',
    borderColor: '#EC4899',
    textColor: '#1a1a1a',
  },
  {
    category: 'demo_request',
    group: 'conversion',
    label: 'Demo Request',
    iconName: 'Presentation',
    primaryColor: '#06B6D4',
    secondaryColor: '#0891B2',
    backgroundColor: '#CFFAFE',
    borderColor: '#06B6D4',
    textColor: '#1a1a1a',
  },
  {
    category: 'consultation',
    group: 'conversion',
    label: 'Consultation',
    iconName: 'Users',
    primaryColor: '#14B8A6',
    secondaryColor: '#0D9488',
    backgroundColor: '#CCFBF1',
    borderColor: '#14B8A6',
    textColor: '#1a1a1a',
  },
]

const CATEGORY_MAP = new Map<NodeCategory, NodeTypeConfig>(
  ALL_NODE_CONFIGS.map((config) => [config.category, config])
)

/**
 * Get the configuration for a specific node category.
 * @param category - The node category to look up
 * @returns The node configuration
 * @throws Error if the category is not found
 */
export function getNodeConfig(category: NodeCategory): NodeTypeConfig {
  const config = CATEGORY_MAP.get(category)
  if (!config) {
    throw new Error(`Unknown node category: ${category}`)
  }
  return config
}

/**
 * Get all node configurations for a specific group.
 * @param group - The node category group to filter by
 * @returns Array of node configurations in the group
 */
export function getNodeByGroup(group: NodeCategoryGroup): NodeTypeConfig[] {
  return ALL_NODE_CONFIGS.filter((config) => config.group === group)
}
